spring.application.name=demo

# Keycloak OIDC - OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.developbranch.cn/realms/bsr

# MariaDB DataSource
spring.datasource.url=jdbc:mariadb://localhost:3306/ers
spring.datasource.username=akka
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
